create database  if not exists project;
USE project;

-- ========== PRODUCT TYPES ==========
CREATE TABLE PRODUCT_TYPE (
  PRODUCT_TYPE_ID int PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  PARENT_TYPE_ID int,
  DESCRIPTION VARCHAR(255),
  FOREIGN KEY (PARENT_TYPE_ID) REFERENCES PRODUCT_TYPE(PRODUCT_TYPE_ID)
);

-- ========== BRANDS ==========
CREATE TABLE BRAND (
  BRAND_ID int PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL
);

-- ========== VENDORS ==========
CREATE TABLE VENDOR (
  VENDOR_ID int PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  ADDRESS VARCHAR(200),
  PHONE VARCHAR(20),
  EMAIL VARCHAR(100)
);

-- ========== PRODUCTS ==========
CREATE TABLE PRODUCT (
  PRODUCT_ID int PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  UPC_CODE VARCHAR(50) UNIQUE NOT NULL,
  SIZE VARCHAR(50),
  PACKAGING VARCHAR(50),
  BRAND_ID int,
  PRODUCT_TYPE_ID int,
  VENDOR_ID int,
  FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID),
  FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE(PRODUCT_TYPE_ID),
  FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(VENDOR_ID)
);

-- ========== STORES ==========
CREATE TABLE STORE (
  STORE_ID int PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  ADDRESS VARCHAR(200),
  CITY VARCHAR(100),
  STATE VARCHAR(100),
  ZIP_CODE VARCHAR(10),
  OPENING_HOURS VARCHAR(100)
);

-- ========== CUSTOMERS ==========
CREATE TABLE CUSTOMER (
  CUSTOMER_ID int PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100),
  PHONE VARCHAR(20),
  ADDRESS VARCHAR(200),
  GENDER CHAR(1) CHECK (GENDER IN ('M','F','O'))
);

CREATE TABLE TRANSACTION (
  TRANSACTION_ID int PRIMARY KEY,
  STORE_ID int,
  CUSTOMER_ID int,
  TRANSACTION_DATE DATE,
  FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE TRANSACTION_ITEM (
  TRANSACTION_ID int,
  PRODUCT_ID int,
  QUANTITY int,
  PRICE int(10),
  FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION(TRANSACTION_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);
