-- PostgreSQL Database Schema for DBMS Project

-- Drop existing tables if they exist (in reverse order due to foreign keys)
DROP TABLE IF EXISTS TRANSACTION_ITEM;
DROP TABLE IF EXISTS "TRANSACTION";
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS STORE;
DROP TABLE IF EXISTS VENDOR;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS PRODUCT_TYPE;

-- ========== PRODUCT TYPES ==========
CREATE TABLE PRODUCT_TYPE (
  PRODUCT_TYPE_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  PARENT_TYPE_ID INTEGER,
  DESCRIPTION VARCHAR(255),
  FOREIGN KEY (PARENT_TYPE_ID) REFERENCES PRODUCT_TYPE(PRODUCT_TYPE_ID)
);

-- ========== BRANDS ==========
CREATE TABLE BRAND (
  BRAND_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL
);

-- ========== VENDORS ==========
CREATE TABLE VENDOR (
  VENDOR_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  ADDRESS VARCHAR(200),
  PHONE VARCHAR(20),
  EMAIL VARCHAR(100)
);

-- ========== PRODUCTS ==========
CREATE TABLE PRODUCT (
  PRODUCT_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  UPC_CODE VARCHAR(50) UNIQUE NOT NULL,
  SIZE VARCHAR(50),
  PACKAGING VARCHAR(50),
  BRAND_ID INTEGER,
  PRODUCT_TYPE_ID INTEGER,
  VENDOR_ID INTEGER,
  FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID),
  FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE(PRODUCT_TYPE_ID),
  FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(VENDOR_ID)
);

-- ========== STORES ==========
CREATE TABLE STORE (
  STORE_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  ADDRESS VARCHAR(200),
  CITY VARCHAR(100),
  STATE VARCHAR(100),
  ZIP_CODE VARCHAR(10),
  OPENING_HOURS VARCHAR(100)
);

-- ========== CUSTOMERS ==========
CREATE TABLE CUSTOMER (
  CUSTOMER_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100),
  PHONE VARCHAR(20),
  ADDRESS VARCHAR(200),
  GENDER CHAR(1) CHECK (GENDER IN ('M','F','O'))
);

-- ========== TRANSACTIONS ==========
-- Note: Using double quotes for "TRANSACTION" since it's a reserved word in PostgreSQL
CREATE TABLE "TRANSACTION" (
  TRANSACTION_ID SERIAL PRIMARY KEY,
  STORE_ID INTEGER,
  CUSTOMER_ID INTEGER,
  TRANSACTION_DATE DATE,
  FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- ========== TRANSACTION ITEMS ==========
CREATE TABLE TRANSACTION_ITEM (
  TRANSACTION_ID INTEGER,
  PRODUCT_ID INTEGER,
  QUANTITY INTEGER,
  PRICE DECIMAL(10,2),
  FOREIGN KEY (TRANSACTION_ID) REFERENCES "TRANSACTION"(TRANSACTION_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
  PRIMARY KEY (TRANSACTION_ID, PRODUCT_ID)
);